#Name:  Jonathan Ho
#Email:  jlh5360@rit.edu
#Date:  2/2/2024


---
- name: Install SSHD and Git service   #Playbook to install SSHD and Git on Linux (target)
  hosts: linux   #Specifies the target hosts or group of hosts based on the inventory file
  become: true   #Allows the tasks to be executed with root privileges
  tasks:
    - name: Install SSHD   #Task to install the SSHD package
      apt:   #Installs packages
        name: openssh-server   #The package name (openssh-server) to install
        state: present   #Ensures that the package (openssh-server) is present on the system
        
    - name: Start SSHD   #Task to start the SSHD service
      service:   #Manages services
        name: sshd   #The service name to manage (sshd --> SSH daemon)
        state: started   #Ensures that the service (sshd --> SSH daemon) is started
        enabled: true   #Enables the service (sshd --> SSH daemon) start on boot
        
    - name: Install Git   #Task to install Git
      apt:   #Installs packages
        name: git   #The package name (git) to install
        state: present   #Ensures that the package (git) is present on the system
