#Name:  Jonathan Ho
#Email:  jlh5360@rit.edu
#Date:  2/2/2024


---
- name: Start WinRM & install OpenSSH & create user   #Playbook to start WinRM & install OpenSSH & create user & create a user on Windows (target)
  hosts: windows   #Specifies the target hosts or group of hosts based on the inventory file
  tasks:        
    - name: Start WinRM service   #Task to start WinRM service
      ansible.windows.win_service:
        name: winrm   #The service name (winrm) to start
        start_mode: auto   #Ensures that the service is on auto on boot
        state: started   #Ensure that the feature is started
    
    - name: Install OpenSSH Server   #Task to install OpenSSH Server
      #Will run the command "Add-WindowsCapability -Online -Name OpenSSH*" in Windows
      #Powershell to install OpenSSH
      ansible.windows.win_shell: Add-WindowsCapability -Online -Name OpenSSH*
        
    - name: Start OpenSSH Server   #Task to start OpenSSH Server
      ansible.windows.win_service:
        name: sshd   #The service name (sshd) to start
        start_mode: auto   #Ensures that the service is on auto on boot
        state: started   #Ensure that the feature is started
        
    - name: Create a new user   #Tasks to create a new user
      ansible.windows.win_user:
        name: testuser   #Sets the name
        password: testuser   #Sets the password
        state: present   #Ensures that the user (testuser) is present on the system
        groups: Administrators   #Adds the user (testuser) as an administrator
